interface BasicInformation {
  full_name: String!,
  address: String!,
  created_at: Date,
  updated_at: Date
}


type Customer implements BasicInformation {
  id: ID!,
  full_name: String!,
  address: String!,
  created_at: Date,
  updated_at: Date
}

input CustomerPayload {
  full_name: String!,
  address: String!
}




